baseurl = "http://masgai.com"
languageCode = "en-us"
title = "Al Masgai"
staticDir = "static"
config = "config.toml"
defaultContentLanguage = "en"
theme = "kiss"
publishDir = "site"

[params.info]
homeTitle = "Al Masgai"

[params.social]
github = "almasgai"
email = "alex.masgai@gmail.com"
linkedin = "al-masgai"

[params.assets]
customCSS = ["css/custom.css"]
