baseurl = "http://masgai.com"
languageCode = "en-us"
title = "Al Masgai"
staticDir = "static"
config = "config.toml"
defaultContentLanguage = "en"
theme = "tale" 
publishDir = "docs"

[params.info]
homeTitle = "Al Masgai"

[params.social]
github = "almasgai"
email = "alex.masgai@gmail.com"
linkedin = "al-masgai"

[params.assets]
customCSS = ["css/custom.css"]

[taxonomies]
tag = ["electronics", "arduino", "C", "C++", "Python", "Mobile", "School"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "sorting"
    name = "Sorting"
    title = "Sorting"
    url = "/sorting/"
    weight = 3
  [[menu.main]]
    identifier = "pathfinding"
    name = "Pathfinding"
    title = "Pathfinding"
    url = "/pathfinding/"
    weight = 4
